### ISSUE TITLE
Montar o sistema de rótulos para issues

### ISSUE THREAD

**Issue by lubianat** [lubianat/bioinfo_brasil#12]
- [x] organização do repositório
- [x] modelagem de dados
- [x] documentação
- [x] tutoriais
- [x] tempestade cerebral
- [x] mapeamento de informações
- [ ] raspagem

**Comment by lubianat** [comment]
Atualizar em https://github.com/lubianat/bioinfo_brasil/blob/master/labels.md

**Comment by jvfe** [comment]
Colocar descrições pros rótulos criados: https://github.com/lubianat/bioinfo_brasil/labels
