### ISSUE TITLE
Melhorar o template para raspagem de pessoas afiliadas a instituições

### ISSUE THREAD

**Issue by lubianat** [lubianat/bioinfo_brasil#30]
Template aqui: https://colab.research.google.com/drive/1_ZPZIufl6nrQz7qmRnugi98iqPQkUzug

**Comment by jvfe** [comment]
Traduzi o template, melhorei algumas seções e adicionei ao repositório https://colab.research.google.com/github/lubianat/bioinfo_brasil/blob/master/tutorial/template_raspar_scholia.ipynb

**Comment by lubianat** [comment]
@jvfe show de bola!!

Umas coisas preu fazer depois: 
- [ ] Esconder output de células inúteis
- [ ] Adicionar print-screens e tutoriais de 
- [ ] Adaptar o exemplo (está para o X-Meeting, seria bom ter para uma organização)
